nav:
  Home: /
  Search: /Search/
  # About: /about/
  # Writing: /posts/
  Github: http://github.com/chenkxin

projects_url: http://github.com/chenkxin

customize:
    gravatar:
        email: 
    logo:
        enabled: true
        width: 50
        height: 50
        url: /images/hacker.png
        gravatar: false
    favicon: 
      # eg. generate with http://realfavicongenerator.net/
      desktop:
        url: /images/hacker.png
        gravatar: false
      android:
        url: /images/hacker.png
        gravator: false
      apple:
        url: /images/hacker.png
        gravator: false
    social_links:
        github: http://github.com/chenkxin
    show_all_posts: false
    post_count: 10
    highlight: pojoaque

# RSS
rss: false

# Plugins
plugins:
    disqus_shortname: # Disqus Comments Shortname
    # google_analytics: G-PW6NFGW881 # enter the tracking ID for your Google Analytics

# Miscellaneous
miscellaneous:
    open_graph: # see http://ogp.me
        fb_app_id:
        fb_admins:
        twitter_id:
        google_plus:
